export const ActionTypes = {
  FETCH_LIST_REQUEST: 'FETCH_LIST_REQUEST',
  FETCH_MORE_REQUEST: 'FETCH_MORE_REQUEST',
  FETCH_LIST_SUCCESS: 'FETCH_LIST_SUCCESS',
  FETCH_LIST_ERROR: 'FETCH_LIST_ERROR',
  UPDATE_CART_COUNTER: 'UPDATE_CART_COUNTER',
};
